const VueLoaderPlugin = require('vue-loader/lib/plugin') ///vue需要
const path=require('path')
module.exports={
    entry:{
        main:'./src/main.js'
    },
    mode:'development',
    output:{
        filename:'[name].js',
        path:path.resolve(__dirname,'./dist'),
        publicPath:'./'
    },
    devServer:{
        contentBase:'dist',
        overlay:true,
    },
    plugins:[
        new VueLoaderPlugin()
    ],
    resolve:{
        alias:{
            'vue$':'vue/dist/vue.js'
        }
    },
    module:{
        rules:[
            {
                test:/\.vue$/,
                loader:'vue-loader'
            },
            {
                test:/\.css$/,
                use:[
                    {loader:'style-loader'},
                    {loader:'css-loader'}
                ]
            },
            {
                test:/\.html$/,
                use:[
                    {loader:'file-loader',options:{name:'[name].html'}},
                    {loader:'extract-loader'},
                    {loader:'html-loader'}
                ]
            },
            {
                test:/\.(jpg|png|gif|svg)$/,
                use:[
                    {loader:'file-loader',options:{name:'[name].[ext]'}}
                ]
            }
        ]
    }
}